/**
 * Registers relay-backed models in the agent's own `~/.grok/config.toml`.
 *
 * The file belongs to the user and the CLI, so nothing is reparsed or
 * reformatted: this module owns a marker-delimited block at the end of the file
 * and rewrites only that region. Hand-written sections, comments, and ordering
 * outside the markers survive untouched.
 */

import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const START_MARKER = "# >>> grok-gui managed models — edited automatically >>>";
const END_MARKER = "# <<< grok-gui managed models <<<";

export type ManagedModel = {
  /** TOML section name: `[model.<key>]`. */
  key: string;
  /** Identifier the agent sends upstream. */
  model: string;
  name: string;
  baseUrl: string;
  /**
   * Literal credential. Only for secrets that are local and short-lived, such
   * as the relay's per-launch token. Vendor keys use `envKey` so they never
   * land in a file the user might share.
   */
  apiKey?: string;
  /** Environment variable holding the credential at agent launch. */
  envKey?: string;
  apiBackend: "chat_completions" | "responses" | "messages";
  contextWindow: number;
  maxCompletionTokens?: number;
  /**
   * Advertise reasoning-effort support, which makes the agent send the
   * backend-appropriate effort field. Verified model metadata takes priority;
   * unknown relay models can still use the endpoint's manual fallback.
   */
  reasoningEfforts?: readonly string[];
  /** Effort marked as default in the agent model menu. */
  defaultReasoningEffort?: string;
};

const CONTROL_ESCAPES: Record<string, string> = {
  "\b": "\\b",
  "\t": "\\t",
  "\n": "\\n",
  "\f": "\\f",
  "\r": "\\r",
  '"': '\\"',
  "\\": "\\\\",
};

/** Quote a TOML basic string. */
export function tomlString(value: string): string {
  let out = '"';
  for (const char of value) {
    const escape = CONTROL_ESCAPES[char];
    if (escape) {
      out += escape;
      continue;
    }
    const code = char.codePointAt(0)!;
    out +=
      code < 0x20 || code === 0x7f
        ? `\\u${code.toString(16).padStart(4, "0")}`
        : char;
  }
  return `${out}"`;
}

/** Title-cased menu label for an effort value, e.g. "high" → "High". */
function effortLabel(effort: string): string {
  return effort.charAt(0).toUpperCase() + effort.slice(1);
}

export function renderManagedBlock(models: ManagedModel[]): string {
  const sections = models.map((model) => {
    const lines = [
      `[model.${model.key}]`,
      `model = ${tomlString(model.model)}`,
      `name = ${tomlString(model.name)}`,
      `base_url = ${tomlString(model.baseUrl)}`,
    ];
    if (model.apiKey !== undefined) {
      lines.push(`api_key = ${tomlString(model.apiKey)}`);
    }
    if (model.envKey !== undefined) {
      lines.push(`env_key = ${tomlString(model.envKey)}`);
    }
    lines.push(
      `api_backend = ${tomlString(model.apiBackend)}`,
      `context_window = ${model.contextWindow}`,
    );
    if (model.reasoningEfforts?.length) {
      const defaultEffort = model.defaultReasoningEffort;
      const entries = model.reasoningEfforts.map(
        (effort, index) =>
          `{ id = ${tomlString(effort)}, value = ${tomlString(effort)}, ` +
          `label = ${tomlString(effortLabel(effort))}, default = ${
            defaultEffort ? effort === defaultEffort : index === 0
          } }`,
      );
      lines.push(
        "supports_reasoning_effort = true",
        `reasoning_efforts = [${entries.join(", ")}]`,
      );
    }
    if (model.maxCompletionTokens !== undefined) {
      lines.push(`max_completion_tokens = ${model.maxCompletionTokens}`);
    }
    return lines.join("\n");
  });

  return [
    START_MARKER,
    "# Generated by the desktop app. Changes inside this block are overwritten;",
    "# the local relay port and token change on every launch.",
    "",
    ...(sections.length ? [sections.join("\n\n"), ""] : []),
    END_MARKER,
  ].join("\n");
}

/**
 * Replace (or drop, when `block` is null) the managed region of a config file.
 * Returns the new file contents.
 */
export function applyManagedBlock(
  existing: string,
  block: string | null,
): string {
  const start = existing.indexOf(START_MARKER);
  const endMarkerAt = existing.indexOf(END_MARKER);
  const hasRegion = start !== -1 && endMarkerAt > start;

  if (hasRegion) {
    const end = endMarkerAt + END_MARKER.length;
    const before = existing.slice(0, start).replace(/\s+$/, "");
    const after = existing.slice(end).replace(/^\s+/, "");

    const parts: string[] = [];
    if (before) parts.push(before);
    if (block) parts.push(block);
    if (after) parts.push(after);
    return parts.length ? `${parts.join("\n\n")}\n` : "";
  }

  if (!block) return existing;
  const trimmed = existing.replace(/\s+$/, "");
  return trimmed ? `${trimmed}\n\n${block}\n` : `${block}\n`;
}

/** Same resolution order the CLI uses for its home directory. */
export function grokConfigPath(): string {
  const fromEnv =
    process.env.GROK_HOME?.trim() || process.env.GROK_CONFIG_DIR?.trim();
  const home = fromEnv || path.join(os.homedir(), ".grok");
  return path.join(home, "config.toml");
}

function writeFileAtomic(file: string, contents: string): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const tmp = `${file}.tmp`;
  fs.writeFileSync(tmp, contents, "utf8");
  fs.renameSync(tmp, file);
}

/**
 * Write the managed block, leaving the rest of the config untouched. Skips the
 * write when nothing changed so the CLI does not see spurious file events.
 */
export function syncManagedModels(
  models: ManagedModel[],
  configPath: string = grokConfigPath(),
): void {
  let existing = "";
  try {
    existing = fs.readFileSync(configPath, "utf8");
  } catch {
    existing = "";
  }
  const next = applyManagedBlock(
    existing,
    models.length ? renderManagedBlock(models) : null,
  );
  if (next === existing) return;
  writeFileAtomic(configPath, next);
}
